name: Volt Athlete
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18324
title: Prescriptive Strength Training For Elite Athletes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#262a35'
    - '#4c5164'
    - '#a62544'
    - '#767b8f'
  brandStrength: 0.4723194115795195
  lightness: 0.6965751203242689
  saturation: 0.44055981817655265
  rhythmicContrast: 0.3964855126105249
purpose: []
