name: Volt Athlete
favicon: null
layout_spectrum: 0.5129277149681002
typography_spectrum: 0.9391632508486509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4723194115795195
  lightness: 0.6965751203242689
  saturation: 0.44055981817655265
  rhythmicContrast: 0.3964855126105249
purpose: []
